alias v="vagrant"
alias vup="vagrant up"
alias vssh="vagrant ssh"
alias vhalt="vagrant halt"
alias vreload="vagrant reload"
alias vnuke="vagrant destroy -f"
alias vgen="vagrant destroy -f && vagrant up"
alias vprov="vagrant up && vagrant provision"
